services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    command: >
      gunicorn --bind=0.0.0.0:8000 --workers=3 core.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}=value
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: